# Site settings
title: About Yuxiao Shi!!
tag_text: Yuxiao Shi
description: A responsive template for Yuxiao's personal website
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
